language: node_js
node_js:
  - lts/*
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "xAqIpd2M5kE8JsHCmPtvoe0lvqiiImBQyXtxVQDPvvhCcV79SimvZGorQqCGcyOcjFGNOyu2fqZ65cqj3HnlAYaDLn+kTp/UEuca9mlfta7b5b/vxMz/ZcdFuZ1r72Y4hdju5cVwiKmSz82z/y6b7efSZrJDIsztJDwooKLd4Ez15LMglfYaYgJv6K7PitEnRFQze+J1hRp9DA7xKSrfx7GFecCQNlIDKQn90t+HwWO1Tx9svOJZBgnDcvjqmH0l0uNWOMMDrvmpgqPjZpkduK3sk8L589p4dkdcJCrLHb95hoBroTke2TWUcswkDpKdNZgljsHxPcRq9JA83jO3HNSSXOna36BxU+OWp2FZEvHDqCz0Io9Y3dUWyyQZrRZJJZddxgUTxAeeJDcYCq17qdR0yOCpfAO/0AEBOM64SH0HF3fqpYRlB11Ze/TKaTmp1d7HBtnp0S10r6dSDUrEGJcOz8dvrxIlBhwrdjrFlNoH6B6Zhm9A5BTYE46imDmAHL6AbuE+7Gmji70dmCvszow43HWvE/QUA6B+myDY3Qetld9awpKUkMEg3nuhHQI/RQ72nqqPZTG92d5mHHZNFWn9Sqqj84nCVwRDDxEcc0GNbFki7VRT/Mmb42TGEPYLE3u6NXBgqlJEp2YAHBXome+ee6fRTO3V59Y5k0EY3s4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "CBkcA8LF3hEoGxdtIvZgGS/gDAVERbSTQmqCpzSpLiQNQJ8us8nqDQcuEHoqLFbVks2SNRaV44g345hvx7ymzRN8uCDOh7u4s337HWmSuR/8XxwuMfn96jmeQiipTKp0e4N6A1Z4YrY6hSi9V5o5XAVzAEpYkiwtTgAIB8C1/U1NicwReOb36X80XBDchN4SnBcVSdqll/7JrgcfjKhM+4y6YmVzs9lfth3JTOrfp/cenQdo+jvgBwR92F1S5XJe5FcUGDBYZVkveQyFCxIsboeqScwPJH87UKvCSJfwPnahXsO5JhEmx+oz5xgMT0Kp33CZY0ZMc6K8L0FctyZgrzQkIGKOLE/UHmCBvRj9ocHVzoIxq3wm7Rd1atkQS8zgCVcEvouesrYgoGsxfCVaWkasU0faVwBjkmyAhhTlIcTHqaD2Wz+IDO9LDIb0Ku34vMNu5wNHFmcFDYYdgv25NY0dfkYM02O4g4OzRn9tZB9jzkAPVryMTI3NX3wbqcYpWzLFVS3+ibW7MT5DlLLWJpGZAoPgSkQ97S7zFPplq3dOcuqaLeROKt35MukDeR65AX75mmcYt9Kdx3ih8ULl87AdAO30ULaJPUlmgvt6//JAvUIV57B8kzUgdJigNETo1FuwKiFY92lFnp55P41adz0ynXpubnqjYpzngK/6OeA="

before_script:
  - sudo pip install awscli
  - npm install

script:
  - npm run test

deploy:
  provider: script
  script: aws s3 sync src s3://train.heap.fi/ --region eu-west-1 --delete
  on:
    branch: master
