name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: 'http://train.heap.fi'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Install AWS CLI tools
        run: pip install awscli
      - name: Deploy to production
        run: aws s3 sync src s3://train.heap.fi/ --region eu-west-1 --delete
